# Generated by Django 6.1 on 2026-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(choices=[('fruta', 'Fruta'), ('verdura', 'Verdura'), ('proteina', 'Proteína (carne, huevo, leguminosa)'), ('cereal', 'Cereal / tubérculo'), ('lacteo', 'Lácteo')], max_length=10)),
                ('edad_minima_meses', models.PositiveSmallIntegerField(default=6, help_text='Edad mínima recomendada para introducir este alimento (OMS: alimentación complementaria desde los 6 meses).')),
                ('disponible', models.BooleanField(default=True, help_text='Si está desmarcado, este alimento no se usa en los planes nutricionales generados.')),
                ('notas', models.CharField(blank=True, default='', help_text="Ej. 'picar en trozos pequeños para evitar atragantamiento'.", max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grupo', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'grupo'), name='unique_alimento_por_grupo')],
            },
        ),
    ]
