# Generated by Django 6.1 on 2026-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_seed_alimentos_comunitarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='calorias_kcal_100g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Energía por cada 100g/100mL de este alimento, en kcal -- valor de referencia aproximado (tabla de composición de alimentos estándar), no un análisis de laboratorio de este alimento en particular.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='carbohidratos_g_100g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='grasa_g_100g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='porcion_referencia_g',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tamaño de una porción de referencia para un niño pequeño, en gramos (o mL para líquidos). Se usa para calcular el aporte calórico del plan.', null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proteina_g_100g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='region_especifica',
            field=models.CharField(blank=True, choices=[('kogui', 'Kogui'), ('arhuaco', 'Arhuaco')], default='', help_text='Dejar vacío = disponible para cualquier paciente (catálogo general). Si se marca una comunidad (ej. Kogui), este alimento SOLO se ofrece además en el plan de pacientes de esa etnia -- no reemplaza el catálogo general, que se sigue ofreciendo a todos los pacientes tengan o no una etnia registrada.', max_length=10),
        ),
    ]
