# Generated by Django 6.1 on 2026-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_seed_datos_nutricionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='excluido_para_region',
            field=models.CharField(blank=True, choices=[('kogui', 'Kogui'), ('arhuaco', 'Arhuaco')], default='', help_text='Si se marca una comunidad, este alimento (aunque esté en el catálogo general) NO se ofrece a pacientes de esa etnia -- para alimentos que, pese a estar disponibles en general, no son culturalmente apropiados o accesibles para esa comunidad en particular. Use junto con `region_especifica` en el alimento de reemplazo correspondiente.', max_length=10),
        ),
    ]
