# Generated by Django 6.1.1 on 2026-09-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_plan_kogui_tcac'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='cantidad_casera',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ej. 2 (para "2 cucharadas"). Si se deja vacío con una unidad seleccionada, se asume 1.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='descripcion_casera',
            field=models.CharField(blank=True, default='', help_text='Texto libre que reemplaza cantidad+unidad para casos que no encajan en el patrón simple (ej. "1 arepa pequeña", "medio plátano"). Si se llena, tiene prioridad sobre unidad_casera/cantidad_casera.', max_length=100),
        ),
        migrations.AddField(
            model_name='alimento',
            name='unidad_casera',
            field=models.CharField(blank=True, choices=[('cucharada', 'Cucharada'), ('punado', 'Puñado'), ('pizca', 'Pizca'), ('vaso_agua', 'Vaso de agua'), ('chorro', 'Chorro'), ('unidad', 'Unidad / tamaño (ej. "1 arepa pequeña")')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='porcion_referencia_g',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tamaño de una porción de referencia para un niño pequeño, en gramos (o mL para líquidos). Se usa para calcular el aporte calórico del plan -- se sigue guardando aunque el reporte muestre la medida casera (ver campos de abajo), porque el cálculo de calorías/proteína del plan necesita gramos.', null=True),
        ),
    ]
