# Generated by Django 6.1 on 2026-08-07 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.DateField()),
                ('edad_dias', models.PositiveIntegerField()),
                ('edad_meses_decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_medicion_talla', models.CharField(choices=[('acostado', 'Longitud (acostado)'), ('de_pie', 'Estatura (de pie)')], max_length=10)),
                ('perimetro_cefalico_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perimetro_braquial_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edema_bilateral', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completada', 'Completada'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('alerta_critica', models.BooleanField(default=False)),
                ('error_detalle', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='patients.paciente')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_clinico', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='assessments.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(choices=[('TE', 'Talla para la Edad'), ('PT', 'Peso para la Talla'), ('PE', 'Peso para la Edad'), ('IMCE', 'IMC para la Edad'), ('PCE', 'Perímetro Cefálico para la Edad'), ('PBE', 'Perímetro Braquial para la Edad')], max_length=6)),
                ('valor_z', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('clasificacion', models.CharField(max_length=120)),
                ('nivel_alerta', models.CharField(choices=[('normal', 'Normal'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('critico', 'Crítico'), ('no_aplica', 'No aplica')], max_length=10)),
                ('es_bypass', models.BooleanField(default=False)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='assessments.evaluacion')),
            ],
            options={
                'ordering': ['indicador'],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'indicador'), name='unique_indicador_por_evaluacion')],
            },
        ),
    ]
