# Generated by Django 6.1 on 2026-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='pdf_file_familiar',
            field=models.FileField(blank=True, null=True, upload_to='reportes_familiares/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='resumen_familiar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
