# Generated by Django 6.1 on 2026-08-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_reportegenerado_pdf_file_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='plan_nutricional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='tips_nutricionales',
            field=models.TextField(blank=True, default=''),
        ),
    ]
