# Generated by Django 6.1.1 on 2026-09-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_reportegenerado_plan_nutricional_and_more'),
        ('patients', '0003_paciente_comunidad_asentamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_actividad', models.CharField(choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], max_length=10)),
                ('actividades_diarias', models.TextField(blank=True, default='')),
                ('limitaciones', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CalidadMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanza_calibrada', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
                ('instrumentos_validados', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
                ('medicion_repetida', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ContextoFamiliarTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_familiares_baja_talla', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
                ('hermanos_baja_talla', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
                ('inseguridad_alimentaria_reportada', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
                ('dificultad_acceso_salud', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
                ('observaciones_familia', models.TextField(blank=True, default='')),
                ('observaciones_autoridad_tradicional', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='HabitosAlimentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comidas_dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alimentos_frecuentes', models.TextField(blank=True, default='')),
                ('alimentos_escasos', models.TextField(blank=True, default='')),
                ('cambios_recientes_alimentacion', models.TextField(blank=True, default='')),
                ('restricciones_culturales_familiares', models.TextField(blank=True, default='')),
                ('acceso_agua_segura', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('no_reportado', 'No reportado')], default='no_reportado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SignosClinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatiga', models.BooleanField(default=False)),
                ('decaimiento', models.BooleanField(default=False)),
                ('fiebre', models.BooleanField(default=False)),
                ('diarrea', models.BooleanField(default=False)),
                ('vomito', models.BooleanField(default=False)),
                ('perdida_peso_reciente', models.BooleanField(default=False)),
                ('rechazo_alimento', models.BooleanField(default=False)),
                ('deshidratacion', models.BooleanField(default=False)),
                ('dificultad_respiratoria', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='codigo_caso',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='notas_administrativas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='perimetro_cadera_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='perimetro_cintura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='fecha_reporte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='objetivo_reporte',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_caso__gt', '')), fields=('codigo_caso',), name='unique_codigo_caso_si_existe'),
        ),
        migrations.AddField(
            model_name='actividadfisica',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_fisica', to='assessments.evaluacion'),
        ),
        migrations.AddField(
            model_name='calidadmedicion',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_medicion', to='assessments.evaluacion'),
        ),
        migrations.AddField(
            model_name='contextofamiliarterritorial',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contexto_familiar', to='assessments.evaluacion'),
        ),
        migrations.AddField(
            model_name='habitosalimentarios',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos_alimentarios', to='assessments.evaluacion'),
        ),
        migrations.AddField(
            model_name='signosclinicos',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signos_clinicos', to='assessments.evaluacion'),
        ),
    ]
