# Generated by Django 6.1.1 on 2026-09-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_actividadfisica_calidadmedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo_caso',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
