# Generated by Django 6.1 on 2026-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('sintesis_clinica', 'Síntesis clínica (reporte técnico)'), ('sintesis_familiar', 'Síntesis familiar (reporte para la familia)'), ('tips_nutricion', 'Consejos del plan de alimentación')], help_text='Qué nodo del asistente usa este system prompt -- no se puede repetir.', max_length=30, unique=True)),
                ('contenido', models.TextField(help_text='Texto completo del system prompt enviado al LLM antes del mensaje del usuario.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden en que se muestra este prompt en /admin/ -- se puede reordenar sin afectar el funcionamiento del asistente.')),
                ('activo', models.BooleanField(default=True, help_text='Si está desmarcado, el nodo correspondiente usa el texto por defecto de respaldo en vez de este.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt del sistema',
                'verbose_name_plural': 'Prompts del sistema',
                'ordering': ['orden', 'clave'],
            },
        ),
    ]
