# Generated by Django 6.1 on 2026-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.CharField(choices=[('ninguna', 'Ninguna / no indígena'), ('kogui', 'Kogui'), ('arhuaco', 'Arhuaco')], default='ninguna', max_length=10),
        ),
    ]
