# Generated by Django 6.1.1 on 2026-09-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_paciente_etnia'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='comunidad_asentamiento',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cuidador_principal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='lengua_principal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='requiere_mediacion_cultural',
            field=models.BooleanField(default=False),
        ),
    ]
